### PR TITLE
Add download examples

### PR DESCRIPTION
**Pull request by stefpiatek**
Also use vocabularies instead of metadata

To disambiguate between omop metadata tables, kept original name of for vocab version so we won't break things

### CODE REVIEW

**Comment by andysouth** [comment]
@stefpiatek I tried pasting the download code from the readme to check and it 404s - have I done something wrong ?
```
tag = "v4"
relative_path = "data/version.txt"
download_url = glue::glue("https://github.com/SAFEHR-data/omop-vocabs-processed/raw/refs/tags/{tag}/{relative_path}")
download.file(download_url,
              destfile = "version.txt",
              mode = "w")
```
trying URL 'https://github.com/SAFEHR-data/omop-vocabs-processed/raw/refs/tags/v4/data/version.txt'
Error in download.file(download_url, destfile = "version.txt", mode = "w") : 
  cannot open URL 'https://github.com/SAFEHR-data/omop-vocabs-processed/raw/refs/tags/v4/data/version.txt'
'404 Not Found'

**Comment by stefpiatek** [comment]
> @stefpiatek I tried pasting the download code from the readme to check and it 404s - have I done something wrong ?
> 
> ```
> tag = "v4"
> relative_path = "data/version.txt"
> download_url = glue::glue("https://github.com/SAFEHR-data/omop-vocabs-processed/raw/refs/tags/{tag}/{relative_path}")
> download.file(download_url,
>               destfile = "version.txt",
>               mode = "w")
> ```
> 
> trying URL '[`refs`/tags/v4/data/version.txt (raw)](https://github.com/SAFEHR-data/omop-vocabs-processed/raw/refs/tags/v4/data/version.txt)' Error in download.file(download_url, destfile = "version.txt", mode = "w") : cannot open URL '[`refs`/tags/v4/data/version.txt (raw)](https://github.com/SAFEHR-data/omop-vocabs-processed/raw/refs/tags/v4/data/version.txt)' '404 Not Found'

Ah that's because it doesn't exist in main yet (as we renamed it here) - this PR will need to be merged first. I could do one of the other files so that it'll work before we merge?

**Comment by andysouth** [comment]
Aha, yes might be better to use concept.parquet as the example download given that is the one people are likely to want most often. I'm happy to approve now or can wait until you've made changes.

**Review by milanmlft — APPROVED** [review]
🚀

**Review by andysouth — APPROVED** [review]
Looks great @stefpiatek & the R download works for me.
Small thing (that may not be a thing!). That the code blocks in the Readme don't indicate which language they are (R,python,shell) when rendered by Github. For newbies may be worth adding a small heading above each ?

**Comment by stefpiatek** [comment]
> Looks great @stefpiatek & the R download works for me. Small thing (that may not be a thing!). That the code blocks in the Readme don't indicate which language they are (R,python,shell) when rendered by Github. For newbies may be worth adding a small heading above each ?

Yeah that makes sense ✅

**Pull request merged**
